version: "2.4"

services:

  frontend:
    container_name: frontend
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./frontend

  proxy:
    container_name: proxy
    restart: always
    ports:
      - "8080:80"
    links:
      - frontend
    build:
      dockerfile: Dockerfile
      context: ./proxy